config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users, only: [:create, :new]
  resources :books, only: [:index, :show]
  resources :request_borrow_books, only: :create
  resources :authors, only: :show

  resources :books do
    resources :request_borrow_books, only: :new
  end

  namespace :admin do
    resources :request_borrow_books, except: [:edit, :show, :new]
    resources :authors, except: :show
  end
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books, dependent: :restrict_with_exception
  has_many :follow_authors, dependent: :destroy
  has_one_attached :image

  validates :full_name, presence: true
  validates :image,
    content_type:{in: %w[image/jpeg image/gif image/png],
      message: Settings.image.vali },
    size:{less_than: 5.megabytes, message: Settings.image.vali2 }

  scope :sort_by_created_date, ->{order created_at: :desc}

  def display_image_table
    image.variant(resize_to_limit: [Settings.image.table, Settings.image.table])
  end

  def display_image_form
    image.variant(resize_to_limit: [Settings.image.form, Settings.image.form])
  end
end

app/controllers/admin/authors_controller.rb
class Admin::AuthorsController < AdminController
  before_action :set_author,except: [:index, :new, :create]

  def index
    @authors = Author.sort_by_created_date.paginate(page:
      params[:page]).per_page(Settings.author.page)
  end

  def new
    @aut = Author.new()
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def create
    @author = Author.new(author_params)
    @author.image.attach(params[:author][:image])
    @author.save
    respond_to do |format|
      format.js
    end
  end

  def update
    @author.update(author_params)
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @author.destroy
    respond_to do |format|
      format.js
    end
  end

  private

  def set_author
    @author = Author.find_by id: params[:id]
    return @author if @author

    flash[:fails] = t "book.mess.find_fails"
    redirect_to root_url
  end

  def author_params
    params.require(:author).permit(:full_name, :birth_day, :image)
  end

  def check_permission
    return if admin?

    flash[:fails] = t "login.permis"
    redirect_to root_url
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  include SessionsHelper

  before_action :set_author,only: :show

  def show
    @books = Book.joins(
      :author).search_by_author_name(@author.full_name).paginate(page:
        params[:page]).per_page(Settings.author.page)
  end

  private

  def set_author
    @author = Author.find(params[:id])
  end
end

app/views/admin/authors/_author.html.erb
<tr id="<%= author.id if author %>">
  <td><%= image_tag author.display_image_table if author.image.attached? %></td>
  <td><%= author.full_name %></td>
  <td><%= author.birth_day %></td>
  <td>
    <%= link_to t("static_page.edit"), edit_admin_author_path(author),
      class: "edit", remote: true%> |
    <%= link_to t("static_page.destroy"), admin_author_path(author), method: :delete,
      data:{confirm: t("borrow.confirm")} , class: "delete", remote: true %>
  </td>
</tr>

app/views/admin/authors/_form.html.erb
<%= form_with(model: [:admin, author]) do |form| %>
  <div class="row">
    <div class="col-3">
      <%= image_tag author.display_image_form if author.image.attached? %>
    </div>
    <div class="col-9">
      <div class="field">
        <%= form.label :full_name %>
        <%= form.text_field :full_name %>
      </div>
      <div class="field">
        <%= form.label :birth_day %>
        <%= form.date_field :birth_day %>
      </div>
      <span class="image">
        <%= form.file_field :image, accept: "image/jpeg,image/gif,image/png" %>
      </span>
      <div class="actions">
        <%= form.submit %>
      </div>
    </div>
  </div>
<% end %>
<script type="text/javascript">
  $("#author_image").bind("change", function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert("Maximum file size is 5MB. Please choose a smaller file.");
    }
  });
</script>

app/views/admin/authors/create.js.erb
<% if @author.errors.any? %>
  <% @author.errors.full_messages.each do |msg| %>
    var mess = "<%= msg %>";
    alert(mess.replace(/&#39;/g, "\'"));
  <% end %>
<% else %>
  alert("Create success !");
  $("#new-author form").remove()
  $("#new-author a").show()
  $('#author tbody').append("<%= j render @author %>");
<% end %>

app/views/admin/authors/destroy.js.erb
$('.delete').bind('ajax:success', function(){
  $(this).closest('tr').fadeOut();
})

app/views/admin/authors/edit.js.erb
$('.edit').bind('ajax:success', function(){
  $("#new-author form").remove()
  $("#new-author script").remove()
  $("#new-author a").hide()
  $("#new-author").append("<%= j render 'form', author: @author %>")
})

app/views/admin/authors/index.html.erb
<h1><%= t "activerecord.models.author" %></h1>
<div class="row">
  <div class="col-6">
    <table id="author" class="table">
      <thead>
        <th scope="col"><%= t "static_pages.ava" %></th>
        <th scope="col"><%= t "activerecord.attributes.author.full_name" %></th>
        <th scope="col"><%= t "activerecord.attributes.author.birth_day" %></th>
        <th scope="col"><%= t "static_pages.act" %></th>
      </thead>
      <tbody>
        <%= render @authors %>
      </tbody>
    </table>
    <%= will_paginate @authors %>
  </div>
  <div class="col-6">
    <div id="new-author">
      <%= link_to t("author.new"), new_admin_author_path, remote: true %>
    </div>
  </div>
</div>

app/views/admin/authors/new.js.erb
$("#new-author a").hide();
$("#new-author").append("<%= j render 'form', author: @aut %>");

app/views/admin/authors/update.js.erb
$("tr#<%= @author.id %>").replaceWith("<%= j(render @author) %>");
<% if @author.errors.any? %>
  <% @author.errors.full_messages.each do |msg| %>
    var mess = "<%= msg %>";
    alert(mess.replace(/&#39;/g, "\'"));
  <% end %>
<% else %>
  alert("Update success !");
  $("#new-author form").remove()
  $("#new-author a").show()
<% end %>