config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users, only: [:create, :new]
  resources :books, only: [:index, :show]
  resources :request_borrow_books, only: :create
  resources :authors, only: :show

  resources :books do
    resources :request_borrow_books, only: :new
  end

  namespace :admin do
    resources :request_borrow_books, except: [:edit, :show, :new]
    resources :authors, except: :show
  end
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books, dependent: :restrict_with_exception
  has_many :follow_authors, dependent: :destroy
  has_one_attached :image

  validates :full_name, presence: true
  validates :image,
    content_type:{in: %w[image/jpeg image/gif image/png],
      message: Settings.image.vali },
    size:{less_than: 5.megabytes, message: Settings.image.vali2 }

  scope :sort_by_created_date, ->{order created_at: :desc}

  def display_image_table
    image.variant(resize_to_limit: [Settings.image.table, Settings.image.table])
  end

  def display_image_form
    image.variant(resize_to_limit: [Settings.image.form, Settings.image.form])
  end
end

app/controllers/admin/authors_controller.rb
class Admin::AuthorsController < AdminController
  before_action :set_author,except: [:index, :new, :create]

  def index
    @authors = Author.sort_by_created_date.paginate(page:
      params[:page]).per_page(Settings.author.page)
  end

  def new
    @aut = Author.new()
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def create
    @author = Author.new(author_params)
    @author.image.attach(params[:author][:image])
    @author.save
    respond_to do |format|
      format.js
    end
  end

  def update
    @author.update(author_params)
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @author.destroy
    respond_to do |format|
      format.js
    end
  end

  private

  def set_author
    @author = Author.find_by id: params[:id]
    return @author if @author

    flash[:fails] = t "book.mess.find_fails"
    redirect_to root_url
  end

  def author_params
    params.require(:author).permit(:full_name, :birth_day, :image)
  end

  def check_permission
    return if admin?

    flash[:fails] = t "login.permis"
    redirect_to root_url
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  include SessionsHelper

  before_action :set_author,only: :show

  def show
    @books = Book.joins(
      :author).search_by_author_name(@author.full_name).paginate(page:
        params[:page]).per_page(Settings.author.page)
  end

  private

  def set_author
    @author = Author.find(params[:id])
  end
end

app/views/authors/show.html.erb
<div class="row">
  <div class="col-6">
    <h1><%= t "activerecord.models.author" %></h1>
    <div class="col">
      <%= image_tag @author.display_image_form if @author.image.attached? %>
    </div>
    <div class="col">
      <p>
        <strong><%= t "activerecord.attributes.author.full_name" %>:</strong>
        <%= @author.full_name %>
      </p>
      <p>
        <strong><%= t "activerecord.attributes.author.birth_day" %>:</strong>
        <%= @author.birth_day %>
      </p>
    </div>
  </div>
  <div class="col-6">
    <h1><%= t("book.show") %></h1>
    <% @books.each do |book| %>
    <div class="card book-card-mr col-md-4">
      <div class="card-img-top">
        <%= image_tag("image_195509_1_12629.jpg", size: "150x150",
        :alt => t("book.index_attr.no_images")) %>
      </div>
      <div class="card-body">
        <p><%= book.name %></p>
        <div class="row">
          <%= link_to t("book.index_attr.show"), book %>
          <%= form_tag(new_book_request_borrow_book_path(
          book.id), method: :get) do%>
          <%= text_field_tag :locale, params[:locale], hidden: :true %>
          <%= submit_tag t("book.index_attr.borrow")%>
          <% end if logged_in? && book.quantity > 0 %>
        </div>
      </div>
    </div>
    <% end %>
    <%= will_paginate @books %>
  </div>
</div>
<%= link_to t("book.show"), books_path %>