config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users, only: [:create, :new]
  resources :books, only: [:index, :show]
  resources :request_borrow_books, only: :create
  resources :authors, only: :show

  resources :books do
    resources :request_borrow_books, only: :new
  end

  namespace :admin do
    resources :request_borrow_books, except: [:edit, :show, :new]
    resources :authors, except: :show
  end
end

app/views/layouts/_footer.html.erb
<div class="card text-center">
  <div class="card-header">
    <%= t "static_pages.copy" %>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active nav-linkss">
        <%= link_to t("static_pages.home"), root_path %>
      </li>
      <li class="nav-item active nav-linkss">
        <%= link_to t("book.show"), books_path %>
      </li>
      <li class="nav-item dropdown nav-linkss">
        <a class="dropdown-toggle" href="#" data-toggle="dropdown">
          <%= t("static_pages.dropdown") %></a>
        <ul class="dropdown-menu">
          <li class="dropdown-item nav-linkss">
            <%= link_to t("static_pages.eng"), locale: "en"%></li>
          <li class="dropdown-item nav-linkss">
            <%= link_to t("static_pages.vie"), locale: "vi"%></li>
        </ul>
      </li>
      <% if logged_in? %>
      <li class="dropdown navbar-nav nav-linkss">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          <%= t("static_pages.account") %> <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><%= link_to t("static_pages.profile"), "#{}" %></li>
          <li><%= link_to t("static_pages.setting"), "#" %></li>
          <li class="divider"></li>
          <li>
            <%= link_to t("static_pages.log_out"),
              logout_path, method: :delete %>
          </li>
        </ul>
      </li>
      <% else %>
        <li class="navbar-nav nav-linkss">
          <%= link_to t("static_pages.login"), login_path %>
        </li>
      <% end %>
      <% if admin? %>
        <li class="navbar-nav nav-linkss">
          <%= link_to t("admin.request"), admin_request_borrow_books_path %>
        </li>
        <li class="navbar-nav nav-linkss">
          <%= link_to t("static_pages.author"), admin_authors_path %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag "application", media: "all",
  "data-turbolinks-track": "reload" %>
<%= javascript_pack_tag "application",
  "data-turbolinks-track": "reload" %>
<%= stylesheet_link_tag "static_pages" %>
<%= stylesheet_link_tag "book" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= render "layouts/shim" %>
</head>
<body>
  <%= render "layouts/header" %>
  <div class = "container">
    <% flash.each do |message_type, message| %>
      <div class="<%= message_type %>" style=""><%= message %></div>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </div>
  <%= render "layouts/footer" %>
</body>
</html>